version: "3.5"
services:
  es:
    image: elasticsearch:8.0.0
    environment:
      discovery: "type=single-node"
      ELASTIC_PASSWORD: "example"
      KIBANA_PASSWORD: "example"
    ports:
      - "9200:9200"
      - "9300:9300"
  kafka:
    image: bitnami/kafka:3-debian-10
    environment:
      KAFKA_CLIENT_USERS: "kafka"
      KAFKA_CLIENT_PASSWORDS: "example"
      ALLOW_PLAINTEXT_LISTENER: "yes"
  etcd:
    image: quay.io/coreos/etcd:v3.3
    container_name: "etcd"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
  etcd_keeper:
    image: evildecay/etcdkeeper:latest
    environment:
      HOST: "0.0.0.0"
    ports:
      - "12000:8080"
    depends_on:
      - etcd
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: "example"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  redis:
    image: bitnami/redis:6.2-debian-10
    environment:
      REDIS_PASSWORD: "example"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.1/24
