version: "3.5"
services:
  es:
    image: elasticsearch:8.0.0
    environment:
      discovery.type: "single-node"
      ingest.geoip.downloader.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.enabled: "false"
      proxy_disable: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTIC_PASSWORD: "example"
      KIBANA_PASSWORD: "example"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      default:
        ipv4_address: 10.10.0.9
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - "5601:5601"
    networks:
      default:
        ipv4_address: 10.10.0.2
    environment:
      SERVER_PUBLICBASEURL: "http://0.0.0.0:5601"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: "http://es:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "example"
    depends_on:
      - es
  kafka:
    image: bitnami/kafka:3.1.0
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://10.20.0.1:9092,EXTERNAL://10.20.0.1:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      default:
        ipv4_address: 10.10.0.3
  etcd:
    image: quay.io/coreos/etcd:v3.3
    container_name: "etcd"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    networks:
      default:
        ipv4_address: 10.10.0.4
  etcd_keeper:
    image: evildecay/etcdkeeper:latest
    environment:
      HOST: "0.0.0.0"
    ports:
      - "12000:8080"
    networks:
      default:
        ipv4_address: 10.10.0.5
    depends_on:
      - etcd
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: "example"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 10.10.0.6
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 10.10.0.7
  redis:
    image: bitnami/redis:6.2-debian-10
    environment:
      REDIS_PASSWORD: "example"
    ports:
      - '6379:6379'
    networks:
      default:
        ipv4_address: 10.10.0.8

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.1/24
